# https://pre-commit.com/
ci:
    autofix_prs: false
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-added-large-files
      - id: check-yaml

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
       - id: flake8

  - repo: local
    hooks:
       - id: pydoc-markdown
         name: pydoc-markdown
         language: python
         additional_dependencies: ["pydoc-markdown==4.5.0"]
         entry: bash -c 'pydoc-markdown -I nsv/ > docs/api.md'
         pass_filenames: false
