name: nordic-seas-validation
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cf_xarray
  - dask
  - gsw
  - netCDF4
  - pandas
  - pooch
  - scipy
  - xarray
  - numpy
  - matplotlib
  - ipython
  - cartopy
