name: nordic-seas-validation
channels:
  - conda-forge
dependencies:
  - bottleneck
  - cf_xarray
  - dask
  - gsw
  - netCDF4
  - pandas
  - pooch
  - scipy
  - xarray<=2022.03.0
  - numpy
  - matplotlib
  - ipython
  - cartopy
  - geopy
  - xoak
  - scikit-learn
  - pys2index
